name: Despliegue Manual Backend (Oracle Ampere)

on:
  workflow_dispatch: # Esto habilita el botón manual en GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en Oracle via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          port: 4422
          script: |
            mkdir -p ~/nutrition-app
            cd ~/nutrition-app

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi
            
            cd backend
            npm install
            npm run build
            
            pm2 restart backend-app || pm2 start dist/app.js --name "backend-app"